# Generated by Django 4.0.2 on 2022-03-09 07:58

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambiente_nombre', models.CharField(max_length=100)),
                ('ambiente_ubicacion', models.CharField(max_length=200)),
                ('ambiente_tipo', models.IntegerField(choices=[(0, 'SUMINISTROS'), (1, 'AULAS'), (2, 'AUDITORIOS'), (3, 'OFICINAS'), (4, 'LABORATORIOS'), (9, 'OBSOLETOS')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimiento_fecha', models.DateTimeField()),
                ('movimiento_tipo', models.IntegerField(default=1)),
                ('movimiento_estado', models.CharField(choices=[('realizado', 'Realizado'), ('proceso', 'Proceso')], default='realizado', max_length=20)),
                ('movimiento_observaciones', models.CharField(max_length=500)),
                ('ambiente_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ambiente_destino', to='api.ambiente')),
                ('ambiente_origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ambiente_origen', to='api.ambiente')),
                ('movimiento_usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(max_length=200)),
                ('producto_fecreg', models.DateTimeField()),
                ('producto_estado', models.CharField(choices=[('VIGENTE', 'VIGENTE'), ('ANULADO', 'ANULADO')], default='VIGENTE', max_length=20)),
                ('producto_imgurl', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image')),
                ('producto_unidad', models.CharField(choices=[('UN', 'UNIDAD'), ('LT', 'LITROS'), ('KG', 'KILOGRAMOS'), ('PQ', 'PAQUETE')], default='UN', max_length=2)),
                ('categoria_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movdetalle_estado', models.CharField(choices=[('realizado', 'Realizado'), ('proceso', 'Proceso')], default='realizado', max_length=20)),
                ('movdetalle_cantidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('movdetalle_sku', models.CharField(max_length=100)),
                ('movdetalle_glosa', models.CharField(max_length=500)),
                ('movimiento_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.movimiento')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.producto')),
            ],
        ),
    ]
