# Generated by Django 4.0.2 on 2022-03-10 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='movimiento_estado',
            field=models.CharField(choices=[('vigente', 'Vigente'), ('anulado', 'Anulado')], default='realizado', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='movimiento_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimientodetalle',
            name='movdetalle_estado',
            field=models.CharField(choices=[('vigente', 'Vigente'), ('anulado', 'Anulado')], default='realizado', max_length=20),
        ),
    ]
