# Generated by Django 4.0.2 on 2022-02-23 07:40

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimiento_fecha', models.DateTimeField()),
                ('movimiento_tipo', models.IntegerField(default=1)),
                ('movimiento_estado', models.CharField(choices=[('realizado', 'Realizado'), ('proceso', 'Proceso')], default='realizado', max_length=20)),
                ('movimiento_observaciones', models.CharField(max_length=500)),
                ('ambiente_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.ambiente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(max_length=200)),
                ('producto_fecreg', models.DateTimeField()),
                ('producto_estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('bueno', 'Bueno'), ('malo', 'Malo')], default='nuevo', max_length=20)),
                ('producto_imgurl', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image')),
                ('producto_unidad', models.CharField(max_length=5)),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movdetalle_estado', models.CharField(choices=[('realizado', 'Realizado'), ('proceso', 'Proceso')], default='realizado', max_length=20)),
                ('movdetalle_cantidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('movdetalle_sku', models.CharField(max_length=100)),
                ('movdetalle_glosa', models.CharField(max_length=500)),
                ('movimiento_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.movimiento')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.producto')),
            ],
        ),
    ]
