# Generated by Django 4.0.2 on 2022-03-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_movimiento_movimiento_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='movimiento_estado',
            field=models.CharField(choices=[('vigente', 'Vigente'), ('anulado', 'Anulado')], default='vigente', max_length=20),
        ),
    ]
