# Generated by Django 4.0.2 on 2022-03-05 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_remove_movimiento_ambiente_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='movimiento_usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='ambiente_tipo',
            field=models.IntegerField(choices=[(0, 'SUMINISTROS'), (1, 'AULAS'), (2, 'AUDITORIOS'), (3, 'OFICINAS'), (4, 'LABORATORIOS'), (9, 'OBSOLETOS')], default=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto_estado',
            field=models.CharField(choices=[('VIGENTE', 'VIGENTE'), ('ANULADO', 'ANULADO')], default='VIGENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto_unidad',
            field=models.CharField(choices=[('UN', 'UNIDAD'), ('LT', 'LITROS'), ('KG', 'KILOGRAMOS'), ('PQ', 'PAQUETE')], default='UN', max_length=2),
        ),
    ]
